# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_mailid', models.CharField(blank=True, max_length=128, null=True)),
                ('phnum', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('doj', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('presentaddress', models.TextField(blank=True, null=True)),
                ('permanentaddress', models.TextField(blank=True, null=True)),
                ('HQualification', models.IntegerField(blank=True, choices=[(0, 'SSCbelow'), (1, 'SSC'), (2, 'Graduate'), (3, 'Graduate and Above')], default=3, null=True)),
                ('bankac', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='/home/sam/Headrun_Intra/static/uploads/img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
